### ISSUE TITLE
Logikai hiba

### ISSUE THREAD

**Issue by Amynas94** [pythontudasepites/minesweeper#1]
A minesweeper_model.py állományban a 12. sorban, a sor és oszlop ellenőrzésnél kétszer van vizsgálva a row_count, pedig logikailag a row_count és ‎column_count vizsgálat kéne a komment, és a felhasználói üzenet alapján.

**Comment by pythontudasepites** [comment]
Kedves Amynas94!
Köszönöm a visszajelzést. A hibát javítottam.
És köszönöm az alapos átnézésre fordított időt.
